
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_DROIDS_PENDING = 'REQUEST_DROIDS_PENDING';
export const REQUEST_DROIDS_SUCCESS = 'REQUEST_DROIDS_SUCCESS';
export const REQUEST_DROIDS_FAILED = 'REQUEST_DROIDS_FAILED';
